services:
  mongodb:
    image: mongo:8.2
    container_name: inventory_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    entrypoint:
      - bash
      - -c
      - |
        echo "c3VwZXJzZWNyZXRrZXlmb3Jtb25nb2RiY2x1c3Rlcgo=" > /data/replica.key
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        exec docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /data/replica.key
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      # Automatically initialize the replica set if it hasn't been initialized yet.
      # Uses the credentials provided above for mongosh authentication.
      test: >
        mongosh --username admin --password secret --authenticationDatabase admin --eval "
        try {
          if (rs.status().ok !== 1) throw new Error();
        } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'localhost:27017' }]
          });
        }"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo-express:
    image: mongo-express
    container_name: inventory_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@mongodb:27017/?directConnection=true&authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    name: inventory_mongodb_data
